apiVersion: apps/v1
kind: Deployment
metadata:
  name: eu-web-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eu-web
  template:
    metadata:
      labels:
        app: eu-web
    spec:
      containers:
        - name: eu-web-container
          image: 882157583740.dkr.ecr.eu-central-1.amazonaws.com/frontend-frankfurt:7a3b6d3
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eu-web-service
spec:
  selector:
    app: eu-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eu-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eu-web-deploy
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
