apiVersion: apps/v1
kind: Deployment
metadata:
  name: seoul-web-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seoul-web
  template:
    metadata:
      labels:
        app: seoul-web
    spec:
      containers:
        - name: seoul-web-container
          image: 882157583740.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-seoul:9454c23
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: seoul-web-service
spec:
  selector:
    app: seoul-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: seoul-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: seoul-web-deploy
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 50
